# Custom Configuration Example
# This file is now updated to use DAILY data with WEEKLY rebalancing logic.

data:
  file_path: "test_data.csv" # Example using a different data source
  date_column: "Date"
  resample_frequency: null # Use raw daily data
  start_date: "2020-06-01"
  end_date: "2021-06-01"
  benchmark_asset: "cad_ig_er_index"
  assets:
    - "cad_ig_er_index"
    - "us_hy_er_index" 
    - "us_ig_er_index"
    - "tsx"
    - "cad_oas"
    - "us_ig_oas"
    - "us_hy_oas"
    - "vix"

portfolio:
  initial_capital: 1000000
  frequency: "D" # Daily frequency for calculations
  fees: 0.001
  slippage: 0.0005
  position_size: 0.95
  leverage: 1.0

reporting:
  output_dir: "outputs/custom_reports"
  generate_html: true
  generate_pdf: false
  include_plots: true
  metrics_precision: 3

# Feature engineering configuration (parameters are now in trading days)
features:
  momentum_periods: [5, 10, 20, 40, 60] # Scaled from [1, 2, 4, 8, 12] weeks
  volatility_windows: [20, 40, 65] # Scaled from [4, 8, 13] weeks
  sma_windows: [20, 40, 65] # Scaled from [4, 8, 13] weeks
  
  include_macd: true
  include_stochastic: true
  include_rsi: true
  include_bollinger: true
  
  include_oas_features: true
  include_vix: true
  include_correlations: true
  include_relative_strength: true
  
  primary_asset: "cad_ig_er_index"

# Modified cross-asset momentum (parameters are now in trading days)
cross_asset_momentum:
  momentum_assets: ["cad_ig_er_index", "us_hy_er_index", "us_ig_er_index", "tsx"]
  momentum_lookback_days: 15  # Scaled from 3 weeks
  min_confirmations: 2

# Enhanced multi-asset momentum (parameters are now in trading days)
multi_asset_momentum:
  momentum_assets_map:
    tsx: "tsx"
    us_hy: "us_hy_er_index"
    cad_ig: "cad_ig_er_index"
  momentum_lookback_days: 30     # Scaled from 6 weeks
  signal_threshold: -0.01
  exit_hold_days: 10     # Scaled from 2 weeks

# Genetic algorithm tuning
genetic_algorithm:
  population_size: 30
  generations: 30
  mutation_rate: 0.15
  crossover_rate: 0.8
  elitism_rate: 0.1

random_seed: 123
verbose: true
log_level: "INFO" 