# Central configuration for all scripts and modules

data:
  # Path to the CSV file we found
  csv_path: "data_pipelines/data_processed/with_er_daily.csv"
  date_column: "Date"  # Updated to match actual column name in CSV
  price_column: "cad_ig_er_index"
  resample_freq: "W-FRI"

strategy:
  type: "momentum"  # or "genetic_algo"
  momentum_lags: [1,2,3,4,6,8,12,13,26,52]
  pop_size: 120
  max_gens: 120
  mut_rate: 0.4
  cross_rate: 0.4
  target_return: 0.7
  random_seed: 7

reporting:
  output_dir: "results/"
  save_plots: true
